Updated requirements for pip 6.0+ to include a session
pip version 6.0 changed the method signature for `pip.req.parse_requirements`.
This means that the setup.py fails with something like:

File "/tmp/pip-build-3xmp1q/tweepy/setup.py", line 18, in <module>
    reqs = [str(req.req) for req in install_reqs]
  File "/home/dougalmatthews/.virtualenvs/tmp-e9ea5ec74c214e7c/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'